"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-07-26 12:34:56.581548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_budget_user_name')
    )
    op.create_table('simplefin_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_url_encrypted', sa.Text(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requests_today', sa.Integer(), nullable=False),
    sa.Column('last_request_date', sa.Date(), nullable=True),
    sa.Column('sync_interval_hours', sa.Integer(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_sync_time', sa.Time(), nullable=True),
    sa.Column('global_requests_today', sa.Integer(), nullable=False),
    sa.Column('account_requests_today', sa.Integer(), nullable=False),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('last_sync_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('on_budget', sa.Boolean(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('simplefin_account_id', sa.String(length=255), nullable=True),
    sa.Column('simplefin_account_name', sa.String(length=255), nullable=True),
    sa.Column('simplefin_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('first_sync_complete', sa.Boolean(), nullable=False),
    sa.Column('last_simplefin_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('simplefin_balance', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reconciled_balance', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'name', name='uq_account_budget_name')
    )
    op.create_table('budget_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'name', name='uq_budget_view_budget_name')
    )
    op.create_table('category_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'name', name='uq_category_group_budget_name')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('transactions_imported', sa.Integer(), nullable=False),
    sa.Column('transactions_skipped', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('system_key', sa.String(length=30), nullable=True),
    sa.Column('color_slot', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'name', name='uq_tag_budget_name'),
    sa.UniqueConstraint('budget_id', 'system_key', name='uq_tag_budget_system_key')
    )
    op.create_index(op.f('ix_tags_budget_id'), 'tags', ['budget_id'], unique=False)
    op.create_table('liabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('liability_type', sa.String(length=30), nullable=False),
    sa.Column('linked_account_id', sa.UUID(), nullable=True),
    sa.Column('manual_balance', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('minimum_payment', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('compounding', sa.String(length=20), nullable=False),
    sa.Column('origination_date', sa.Date(), nullable=True),
    sa.Column('original_principal', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linked_account_id')
    )
    op.create_index(op.f('ix_liabilities_budget_id'), 'liabilities', ['budget_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_group_id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('linked_account_id', sa.UUID(), nullable=True),
    sa.Column('linked_liability_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_group_id'], ['category_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_liability_id'], ['liabilities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_group_id', 'name', name='uq_category_group_name')
    )
    op.create_table('liability_balance_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('liability_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['liability_id'], ['liabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liability_id', 'date', name='uq_liability_snapshot_date')
    )
    op.create_index(op.f('ix_liability_balance_snapshots_liability_id'), 'liability_balance_snapshots', ['liability_id'], unique=False)
    op.create_table('budget_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('assigned', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'month', name='uq_assignment_category_month')
    )
    op.create_table('budget_moves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('from_category_id', sa.UUID(), nullable=True),
    sa.Column('to_category_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_view_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('view_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['view_id'], ['budget_views.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('view_id', 'category_id', name='uq_view_category')
    )
    op.create_table('category_tags',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'tag_id')
    )
    op.create_table('category_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('repeat_frequency', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id')
    )
    op.create_table('payees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_category_id', sa.UUID(), nullable=True),
    sa.Column('transfer_account_id', sa.UUID(), nullable=True),
    sa.Column('mapping_samples', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'name', name='uq_payee_budget_name')
    )
    op.create_table('payee_tags',
    sa.Column('payee_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payee_id', 'tag_id')
    )
    op.create_table('scheduled_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('payee_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('second_day_of_month', sa.Integer(), nullable=True),
    sa.Column('auto_create', sa.Boolean(), nullable=False),
    sa.Column('days_before_reminder', sa.Integer(), nullable=False),
    sa.Column('transfer_account_id', sa.UUID(), nullable=True),
    sa.Column('last_created_date', sa.Date(), nullable=True),
    sa.Column('next_occurrence_date', sa.Date(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entered_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('payee_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('cleared', sa.String(length=20), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(precision=53), nullable=True),
    sa.Column('longitude', sa.Float(precision=53), nullable=True),
    sa.Column('transfer_id', sa.UUID(), nullable=True),
    sa.Column('parent_transaction_id', sa.UUID(), nullable=True),
    sa.Column('is_split', sa.Boolean(), nullable=False),
    sa.Column('import_id', sa.String(length=255), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('import_description', sa.Text(), nullable=True),
    sa.Column('sync_id', sa.String(length=255), nullable=True),
    sa.Column('sync_source', sa.String(length=50), nullable=True),
    sa.Column('scheduled_transaction_id', sa.UUID(), nullable=True),
    sa.Column('linked_transaction_id', sa.UUID(), nullable=True),
    sa.Column('link_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('has_sync_source', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_budget_location', 'transactions', ['budget_id'], unique=False, postgresql_where=sa.text('latitude IS NOT NULL'))
    op.create_index('uq_transactions_account_import_id', 'transactions', ['account_id', 'import_id'], unique=True, postgresql_where=sa.text('import_id IS NOT NULL AND NOT is_deleted'))
    op.create_index('uq_transactions_account_sync_id', 'transactions', ['account_id', 'sync_id'], unique=True, postgresql_where=sa.text('sync_id IS NOT NULL AND NOT is_deleted'))
    op.create_table('reconciliation_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('statement_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('cleared_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('adjustment_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('adjustment_transaction_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['adjustment_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('synced_transaction_id', sa.UUID(), nullable=False),
    sa.Column('manual_transaction_id', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manual_transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['synced_transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_matches')
    op.drop_table('transaction_attachments')
    op.drop_table('reconciliation_snapshots')
    op.drop_index('uq_transactions_account_sync_id', table_name='transactions', postgresql_where=sa.text('sync_id IS NOT NULL AND NOT is_deleted'))
    op.drop_index('uq_transactions_account_import_id', table_name='transactions', postgresql_where=sa.text('import_id IS NOT NULL AND NOT is_deleted'))
    op.drop_index('ix_transactions_budget_location', table_name='transactions', postgresql_where=sa.text('latitude IS NOT NULL'))
    op.drop_table('transactions')
    op.drop_table('scheduled_transactions')
    op.drop_table('payee_tags')
    op.drop_table('payees')
    op.drop_table('category_targets')
    op.drop_table('category_tags')
    op.drop_table('budget_view_categories')
    op.drop_table('budget_moves')
    op.drop_table('budget_assignments')
    op.drop_index(op.f('ix_liability_balance_snapshots_liability_id'), table_name='liability_balance_snapshots')
    op.drop_table('liability_balance_snapshots')
    op.drop_table('categories')
    op.drop_index(op.f('ix_liabilities_budget_id'), table_name='liabilities')
    op.drop_table('liabilities')
    op.drop_index(op.f('ix_tags_budget_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('import_batches')
    op.drop_table('category_groups')
    op.drop_table('budget_views')
    op.drop_table('accounts')
    op.drop_table('simplefin_connections')
    op.drop_table('budgets')
    op.drop_table('users')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
