"""sync run records

Revision ID: cb7388847350
Revises: e3f1a8c5d920
Create Date: 2026-09-15 22:03:56.614826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb7388847350'
down_revision: Union[str, Sequence[str], None] = 'e3f1a8c5d920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('budget_id', sa.UUID(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('bank_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('orphaned_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feed_txn_count', sa.Integer(), nullable=False),
    sa.Column('imported', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('skip_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched', sa.Integer(), nullable=False),
    sa.Column('adopted', sa.Integer(), nullable=False),
    sa.Column('cleared', sa.Integer(), nullable=False),
    sa.Column('review_queued', sa.Integer(), nullable=False),
    sa.Column('removed_pending', sa.Integer(), nullable=False),
    sa.Column('anchored', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['simplefin_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    op.create_index('ix_sync_runs_connection_created', 'sync_runs', ['connection_id', 'created_at'], unique=False)
    op.create_table('sync_run_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_run_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('simplefin_account_id', sa.String(length=255), nullable=True),
    sa.Column('feed_txn_count', sa.Integer(), nullable=False),
    sa.Column('feed_oldest_date', sa.Date(), nullable=True),
    sa.Column('feed_newest_date', sa.Date(), nullable=True),
    sa.Column('imported', sa.Integer(), nullable=False),
    sa.Column('adopted', sa.Integer(), nullable=False),
    sa.Column('reidentified', sa.Boolean(), nullable=False),
    sa.Column('orphaned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_run_accounts')
    op.drop_index('ix_sync_runs_connection_created', table_name='sync_runs')
    op.drop_table('sync_runs')
    # ### end Alembic commands ###
